#!/usr/bin/env bash

#:==============================================================================
#:
#:          FILE:  reg_bold
#:
#:         USAGE:  reg_bold <BOLD_scan> <struct_file>
#:
#:   DESCRIPTION:
#:
#:       OPTIONS:  ---
#:  REQUIREMENTS:  BOLD_scan -
#:          BUGS:  ---
#:         NOTES:  ---
#:        AUTHOR:  Joe Brockmeier, jzb@zonker.net
#:       COMPANY:  Dissociated Press
#:       VERSION:  1.0
#:       CREATED:  05/25/2007 10:31:01 PM MDT
#:      REVISION:  ---
#:==============================================================================

# make sure there are 2 arguements
if [ $# -ne 2 ]; then
  exit 1
fi

# get the full path of the relevant files
BOLD_FILE=`realpath $1`
STRUCT_FILE=`realpath $2`

# split the directory and the filename of the BOLD file
BOLD_dir=`dirname $BOLD_FILE`
BOLD=`basename -- $BOLD_FILE`

#registration
#flirt vs fnirt

#flirt [-options] -in <inputvol> -ref <refvol> -out <outputvol>

# make folders to brain and registration files if they do not exist already
if [ ! -e $BOLD_dir/split ]; then
  mkdir $BOLD_dir/split
fi
if [ ! -e $BOLD_dir/split/brain ]; then
  mkdir $BOLD_dir/split/brain
fi
if [ ! -e $BOLD_dir/split/reg ]; then
  mkdir $BOLD_dir/split/reg
fi

SPLIT_dir="$BOLD_dir/split"
BET_dir="$BOLD_dir/split/brain"
REG_dir="$BOLD_dir/split/reg"

# call fslsplit to split 4D data into a cluster of 3Ds on time
fslsplit $BOLD_FILE $SPLIT_dir/vol

#register and BET
for f in $SPLIT_dir/vol*; do
  #echo $f

  F_name=`basename $f`
  F_ext="${F_name##*.}"
  echo 'Running flirt on '$F_name
  flirt -in $f -ref $STRUCT_FILE -out $F_name'_reg'
  echo 'Output is ' $F_name'_reg'

done



# merge the registration files back in the BOLD directory
# fslmerge -t <output> <input files>
fslmerge -t reged_$BOLD_dir ./split/reg/vol*
#fslmerge -t $SPLIT_dir ${BOLD_dir##[a-zAZ]*\\}
